### ISSUE TITLE
Using 'generate' or 'blend' tool with accessElineOvc Product Specifications gives Error

### ISSUE THREAD

**Issue by haritmaniyar** [Amartus/SonataBlendingTool#3]
As per the description of "sonata-blending-tool-cli generate - Generate code using configuration." section, I am trying to generate the code for Product Specifications. When I provide both product specifications i.e. present under "./spec/sonata/carrierEthernet/accessEline/order" as per new structure, it gives below error.

Command used - 
java -jar blender-1.4.jar generate -d ./spec/sonata/carrierEthernet/accessEline/order -p accessElineOvc.yaml -p carrierEthernetOperatorUni.yaml -c ./spring-server-example.yaml -i ./api/order/productOrderManagement.api.yaml

[main] ERROR com.amartus.sonata.blender.Blender - Error:
java.lang.NullPointerException: null
        at com.amartus.sonata.blender.impl.postprocess.UpdateDiscriminatorMapping.lambda$process$1(UpdateDiscriminatorMapping.java:41)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:302)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:278)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
        at com.amartus.sonata.blender.impl.postprocess.UpdateDiscriminatorMapping.process(UpdateDiscriminatorMapping.java:42)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.amartus.sonata.blender.impl.postprocess.AbstractPostProcessor.processSchemas(AbstractPostProcessor.java:53)
        at com.amartus.sonata.blender.impl.postprocess.AbstractPostProcessor.accept(AbstractPostProcessor.java:48)
        at com.amartus.sonata.blender.cmd.Generate$AmartusGenerator.generate(Generate.java:111)
        at com.amartus.sonata.blender.cmd.Generate.run(Generate.java:79)
        at com.amartus.sonata.blender.Blender.main(Blender.java:51)

But this generation process works when tried with only 1 Product Specification - 
java -jar blender-1.4.jar generate -d ./spec/sonata/carrierEthernet/accessEline/order -p carrierEthernetOperatorUni.yaml -c ./spring-server-example.yaml -i ./api/order/productOrderManagement.api.yaml

Above code works successfully both for 'generate' and 'blend'.

Is there any issue with generate or blend tool?

**Comment by haritmaniyar** [comment]
Update -
Issue is due to accessElineOvc.yaml file. When tried using below command, it provides the error mentioned in above description.
Command used - 
java -jar blender-1.4.jar generate -d ./spec/sonata/carrierEthernet/accessEline/order -p accessElineOvc.yaml -c ./spring-server-example.yaml -i ./api/order/productOrderManagement.api.yaml

**Comment by bartoszm** [comment]
Hi @haritmaniyar, could you please point me to the version of MEF sonata SDK you are using - ideally you could attach it as a zip to this issue. There might be a few reasons for the behavior you observe and I would like to be able to reproduce your issue. 
In addition I will try to provide better explanation of issue (NPE is not very informative) in the next release of the tool.

**Comment by haritmaniyar** [comment]
[MEF-LSO-Sonata-SDK-working-draft.zip](https://github.com/Amartus/SonataBlendingTool/files/6607883/MEF-LSO-Sonata-SDK-working-draft.zip)

Hi ,

I was using the attached MEF Sonata SDK. I saw a new update is added today, I will try to re-run the tool again with new code.

**Comment by bartoszm** [comment]
@haritmaniyar version [1.5](https://github.com/Amartus/SonataBlendingTool/releases/tag/v1.5) - which I just managed to release already contains the fix for your problem. Please verify and let me know whether it solves it for you.

**Comment by haritmaniyar** [comment]
Hi,
Yes issue now resolved with new version 1.5.
Thank you.
